In [18]:
import tensorflow as tf
import numpy as np

input1=[[10,7],[5,4],[8,3],[2,8],[4,8],[9,1],[6,8],[1,7],[5,3],[7,6]]
output1=[[97],[71],[74],[78],[90],[68],[95],[65],[70],[82]]

with tf.Graph().as_default():
    input = tf.placeholder(tf.float32)
    output = tf.placeholder(tf.float32)

    max_input = tf.reduce_max(input,0)
    max_output = tf.reduce_max(output,0)

    normalized_input = input / max_input
    normalized_output = output / max_output

    wights_1 = tf.Variable(tf.zeros([2,3]))

    wighted_sum = tf.matmul(normalized_input,wights_1)
    activation_1 = tf.sigmoid(wighted_sum)
    
    wights_2 = tf.Variable(tf.zeros([3,1]))
    
    wighted_sum_2 = tf.matmul(normalized_input,wights_2)
    activation_2 = tf.sigmoid(wighted_sum)

    with tf.Session() as se:
        print(se.run(normalized_input, feed_dict = {input:input1,output:output1}))
        print(se.run(normalized_output, feed_dict = {input:input1,output:output1}))

[[ 1.          0.875     ]
 [ 0.5         0.5       ]
 [ 0.80000001  0.375     ]
 [ 0.2         1.        ]
 [ 0.40000001  1.        ]
 [ 0.89999998  0.125     ]
 [ 0.60000002  1.        ]
 [ 0.1         0.875     ]
 [ 0.5         0.375     ]
 [ 0.69999999  0.75      ]]
[[ 1.        ]
 [ 0.73195875]
 [ 0.76288658]
 [ 0.8041237 ]
 [ 0.92783505]
 [ 0.70103091]
 [ 0.97938144]
 [ 0.67010307]
 [ 0.72164947]
 [ 0.84536082]]


In [19]:
import tensorflow as tf

raw_input_data=[[10,7],
                [5,4],
                [8,3],
                [2,8],
                [4,8],
                [9,1],
                [6,8],
                [1,7],
                [5,3],
                [7,6]]

raw_output_data = [97,71,74,78,90,68,95,65,70,82]

with tf.Graph().as_default():
    input = tf.placeholder(tf.float32)
    output = tf.placeholder(tf.float32)
    
    
    max_input = tf.reduce_max(input,0)
    max_output = tf.reduce_max(output,0)
    
    normalized_input = input / max_input
    normalized_output = output / max_output
    
    weights_1 = tf.Variable(tf.zeros([2,3]))
    bias_1 = tf.Variable(tf.zeros([1,3]))
    weighted_sum_1 = tf.matmul(normalized_input, weights_1) + bias_1
    
    activation_1 = tf.sigmoid(weighted_sum_1)
    
    weights_2 = tf.Variable(tf.zeros([3,1]))
    bias_2 = tf.Variable(tf.zeros([1]))
    weighted_sum_2 = tf.matmul(activation_1, weights_2) + bias_2
    
    activation_2 = tf.sigmoid(weighted_sum_2)
    
    loss_1 = tf.reduce_sum((activation_2 - normalized_output)**2)
    
    with tf.Session() as sess:
    
        print((sess.run(normalized_input, feed_dict = {input:raw_input_data,output:raw_output_data})))
        
        print((sess.run(normalized_output, feed_dict = {input:raw_input_data,output:raw_output_data})))

[[ 1.          0.875     ]
 [ 0.5         0.5       ]
 [ 0.80000001  0.375     ]
 [ 0.2         1.        ]
 [ 0.40000001  1.        ]
 [ 0.89999998  0.125     ]
 [ 0.60000002  1.        ]
 [ 0.1         0.875     ]
 [ 0.5         0.375     ]
 [ 0.69999999  0.75      ]]
[ 1.          0.73195875  0.76288658  0.8041237   0.92783505  0.70103091
  0.97938144  0.67010307  0.72164947  0.84536082]


In [20]:
import tensorflow as tf

# Let's define our input and output data.
# Note that this is all observed data, so it is defined as constants.
# The data includes 5 examples and 2 features.
# hours studied  |  hours slept  |  test score
# ---------------------------------------------
#       10       |      7        |     97
#        5       |      4        |     71
#        8       |      3        |     74
#        2       |      8        |     78
#        4       |      8        |     90
#        9       |      1        |     68
#        6       |      8        |     95
#        1       |      7        |     65
#        5       |      3        |     70
#        7       |      6        |     82
# ---------------------------------------------
# Define the raw data that we have observed.
train_input_data = [[10, 7], [5, 4], [8, 3], [2, 8], [4, 8]]
train_output_data = [[97], [71], [74], [78], [90]]

# Number of training examples.
NUM_TRAIN_EXAMPLES = len(train_input_data)

# Store the number of features so we can use it in our neural network structure.
NUM_FEATURES = len(train_input_data[0])

test_input_data = [[9, 1], [6, 8], [1, 7], [5, 3], [7, 6]]
test_output_data = [[68], [95], [65], [70], [82]]

# Number of training steps
EPOCHS = 10000
# Number of neurons in the neural network's hidden layer.
NUM_HIDDEN_LAYER_NEURONS = 3
# Learning rate of our gradient descent optimizer.
LEARNING_RATE = 2.0

graph = tf.Graph()
with graph.as_default():
  # Create a placeholder input tensor.
  input = tf.placeholder(dtype=tf.float32)

  # Create a placeholder for the output tensor (the observed test scores).
  output = tf.placeholder(dtype=tf.float32)

  train_data = {input: train_input_data, output: train_output_data}
  test_data = {input: test_input_data, output: test_output_data}

  # Determine the maximum value of each feature. The result is a 1x2 array.
  max_input = tf.reduce_max(input, 0)

  # Now all of our input values are in the range [0.0, 1.0].
  normalized_input = input / max_input

  # Set up the operations that will normalize the output tensor.
  max_output = tf.reduce_max(output)
  normalized_output = output / max_output

  # Now let's describe the structure of the neural network. We have 2 input features,
  # as described by the input dataset, so this corresponds to 2 nodes in the input
  # layer. Now we want to have a single hidden layer with 3 neurons. Finally, the
  # output layer will only have 1 neuron (the test score).
  num_neurons_1 = NUM_FEATURES
  num_neurons_2 = NUM_HIDDEN_LAYER_NEURONS
  num_neurons_3 = 1

  # Define the weights on the synapses between the input layer and the hidden layer.
  weights_1 = tf.Variable(tf.random_normal([num_neurons_1, num_neurons_2]))

  # Model the bias parameter, as well.
  bias_1 = tf.Variable(tf.random_normal([num_neurons_2]))

  # Compute the weighted sum and add in the bias. Note that bias_1 is 1x3, but the 3 
  # values will be element-wise added to each row in weighted_sums_1, which is 7x3.
  weighted_sums_1 = tf.matmul(normalized_input, weights_1) + bias_1

  # Apply the activation function (sigmoid).
  activation_1 = tf.sigmoid(weighted_sums_1)

  # Do the same steps for the second (output) layer.
  weights_2 = tf.Variable(tf.random_normal([num_neurons_2, num_neurons_3]))
  bias_2 = tf.Variable(tf.random_normal([num_neurons_3]))
  weighted_sums_2 = tf.matmul(activation_1, weights_2) + bias_2
  activation_2 = tf.sigmoid(weighted_sums_2)

  # Define the loss function as the sum of squared differences between observed
  # and computed output.
  loss = tf.reduce_sum((activation_2 - normalized_output)**2) / NUM_TRAIN_EXAMPLES

  # Set up the Stochastic Gradient Descient optimizer to minimize the loss.
  train_step = tf.train.GradientDescentOptimizer(learning_rate=LEARNING_RATE).minimize(loss)

  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    # Run EPOCHS steps of learning.
    for i in range(EPOCHS):
      sess.run(train_step, feed_dict = train_data)
    
    # Here are the trained weights and biases, in case we're interested.
    print('weights_1 =\n{}'.format(sess.run(weights_1)))
    print('bias_1 =\n{}'.format(sess.run(bias_1)))
    print('weights_2 =\n{}'.format(sess.run(weights_2)))
    print('bias_2 =\n{}'.format(sess.run(bias_2)))

    # Does our trained model perform well on the training data?
    print('train data: normalized_output =\n{}'.format(sess.run(normalized_output, feed_dict = train_data)))
    print('train data: activation_2 =\n{}'.format(sess.run(activation_2, feed_dict = train_data)))

    # A good measure of how well we're doing is how small the loss is.
    print('train data: loss = {}'.format(sess.run(loss, feed_dict = train_data)))

    # Does our trained model perform well on the testing data?
    print('test data: normalized_output =\n{}'.format(sess.run(normalized_output, feed_dict = test_data)))
    print('test data: activation_2 =\n{}'.format(sess.run(activation_2, feed_dict = test_data)))

    # A good measure of how well we're doing is how small the loss is.
    print('test data: loss = {}'.format(sess.run(loss, feed_dict = test_data)))      

    # Run it on a couple of new inputs just to see what the model predicts.
    print('unseen data: activation_2 =\n{}'.format(sess.run(activation_2, feed_dict = {input: [[0, 8], [1, 7], [4, 4], [2, 6], [8, 0]]})))

weights_1 =
[[ 2.30110574  0.45575598 -2.14336991]
 [ 2.85978556  1.89326799  0.28729439]]
bias_1 =
[-4.50302267 -1.34895146 -0.34414011]
weights_2 =
[[ 5.38227272]
 [ 1.83954048]
 [-1.8940922 ]]
bias_2 =
[-0.19885498]
train data: normalized_output =
[[ 1.        ]
 [ 0.73195875]
 [ 0.76288658]
 [ 0.8041237 ]
 [ 0.92783505]]
train data: activation_2 =
[[ 0.98139107]
 [ 0.71360326]
 [ 0.78103656]
 [ 0.82409614]
 [ 0.90533304]]
train data: loss = 0.00038357527228072286
test data: normalized_output =
[[ 0.7157895 ]
 [ 1.        ]
 [ 0.68421054]
 [ 0.7368421 ]
 [ 0.86315787]]
test data: activation_2 =
[[ 0.73379475]
 [ 0.96387488]
 [ 0.70938361]
 [ 0.6768896 ]
 [ 0.93023098]]
test data: loss = 0.002071200404316187
unseen data: activation_2 =
[[ 0.71446365]
 [ 0.71726012]
 [ 0.71360326]
 [ 0.7184931 ]
 [ 0.67393786]]
